spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/medical_clinic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

application:
    security:
      jwt:
        secret-key: ${JWT_SECRET}
        expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when_authorized