ALTER TABLE patient
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'PATIENT';

ALTER TABLE doctor
    ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '$2a$10$D8S.1.j.X.g.u.c.k.e.r.s';

ALTER TABLE doctor
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'DOCTOR';

ALTER TABLE patient ALTER COLUMN role DROP DEFAULT;
ALTER TABLE doctor ALTER COLUMN role DROP DEFAULT;
ALTER TABLE doctor ALTER COLUMN password DROP DEFAULT;